<a href="https://colab.research.google.com/github/JeongJinLee-github/THC_Test/blob/master/HelloAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hellow World!!!')
print("AI의 세계로 오신것을 축하합니다. 반갑습니다!!")

hellow World!!!
AI의 세계로 오신것을 축하합니다. 반갑습니다!!


In [5]:
try:
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

In [6]:
print(tf.__version__)

2.3.0


In [14]:
rand = tf.random.uniform([1],0,1)

In [15]:
print(rand)

tf.Tensor([0.5950391], shape=(1,), dtype=float32)


In [20]:
rand_2 = tf.random.uniform([5,],0,1)
print(rand_2)

tf.Tensor([0.06740868 0.16901827 0.34972954 0.45175087 0.7058704 ], shape=(5,), dtype=float32)


In [22]:
rand_2 = tf.random.normal([3,5],0,1)
print(rand_2)

tf.Tensor(
[[-0.34825936 -0.2870502   0.15890151  0.82280517 -0.6764802 ]
 [-0.26516914  0.7487752  -1.3363657  -1.0092747  -0.34565103]
 [-0.36484715 -2.1550374  -2.4190266   0.93397665 -0.44960573]], shape=(3, 5), dtype=float32)
